### ISSUE TITLE
Make score available for use in the annotator/free filter tool 

### ISSUE THREAD

**Issue by rkiko** [ecotaxa/ecotaxa#473]
Right now, one can choose a category filter e.g. circ. => 0.5 and sort by score.

However, choose a category filter score => 0.8 and sort by circ. would allow more efficient sorting.

**Comment by grololo06** [comment]
Hi,
Technically (and from user point of view as well), the score is not a "free" column, i.e. it's not an object_ that can be found in a TSV.
So we'd need to find another place or rename this part of the interface.
I'll discuss the idea with JO & Marc.

**Comment by picheral** [comment]
The possibility of sorting according to multiple variables have been discussed. There is today no "easy" solution. The best would be a clustering (like morpho cluster or simpler) to allow to check for similarities.

**Comment by rkiko** [comment]
Sorting with multiple variables works using the annotator/free filter tool as described above. However, including the score in this possibility would help most. E.g. circ. has some values that have no clear meaning (meaning, I would need to find out what value of circularity is meaningful in each special case I am looking at), so it is difficult to define a good value for data to be shown. Score has a +- clear meaning, values above 0.8 should generally be good. So selecting everything with a high score in a category and then sorting according to another value is very helpful. I have deep_learning_scores as an additional column, I can show you how much it improves the sorting capabilities to constrain the shown images to a high score on that one.

**Comment by jiho** [comment]
I think including the score as a filter in addition to a sorting criterion makes sense. Implementation wise, that can be either a new filter  shown as a two handle slider that would allow to select a range of scores (between 0 and 1) or added to the "free filters".

**Comment by grololo06** [comment]
Fixed in 2.6.2.
