### ISSUE TITLE
Waiting "magnifying glasses" come and go and request never finishes

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa#644]
I know it'll probably be hard to track and will depend on many other factors but the magnifying glasses that are now displayed when a request is in process do not just accumulate: they disappear and come back and seem to flickr (see attached screen recording).

https://user-images.githubusercontent.com/18445/110977031-ef03c480-8361-11eb-9f24-4c29da2cf93f.mov

In addition, I am in a project with 100k images, trying to visualise ~1000, sorted by area; it's Friday 18:30 (so not rush hour) and I've waited several minutes, I've got ~10 lignes full of magnifying glasses but no images. Something seems stuck...
Project 4049, category Coscinodiscophycidae

Can it be because the images are big (colour, high pixel density)?

**Comment by grololo06** [comment]
There is one line of glasses per _in progress_ query, and they are at the same place in the page. So the above shows that you have tried several times to get the data, probably by just changing a display parameter. #561 would help in such case, but it's not a quick fix, as the query cancellation has to go from the user, through all layers down to DB.

**Comment by grololo06** [comment]
Cannot be fixed so I'm closing.
