### ISSUE TITLE
Remove latin-1 encoding export option (or not)

### ISSUE THREAD

**Issue by grololo06** [ecotaxa/ecotaxa#724]
Present page says:

![Capture d’écran de 2021-09-23 05-29-41](https://user-images.githubusercontent.com/20199778/134450860-dadff76c-e7b7-47e0-b08d-36e814c66712.png)

Leave/amend/remove?

**Comment by picheral** [comment]
Pas d'opinion ! Simple is beautifull mais frustrer les gens n'est pas sympa !

**Comment by jiho** [comment]
The only people who know about the encoding problems are those who know how to solve them (i.e. the others would not even know that ticking the option will solve their problem).
UTF-8 is the international standard, we should use this one and only this one.

**Comment by grololo06** [comment]
Done in 2.6.1
