### ISSUE TITLE
Retirer le message de demande de paiement sur la page d'Import.

### ISSUE THREAD

**Issue by picheral** [ecotaxa/ecotaxa#730]

**Comment by grololo06** [comment]
Pour chaque utilisateur ou alors on retire le message pour tout le monde?

**Comment by grololo06** [comment]
Avant le passage chez IFREMER.

**Comment by grololo06** [comment]
Il est aussi dans la page "Create project".

**Comment by grololo06** [comment]
Fixed in 2.6.2.
