### ISSUE TITLE
Show current category in the classification change log

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa#751]
Currently, on the object page, the classification change log table shows the past identifications and the current on is show above. It would be easier and clearer to:
- display the current identification in the table
- display the ids in reverse chronological order (latest first)

<img width="874" alt="Screenshot 2021-12-03 at 13 55 24" src="https://user-images.githubusercontent.com/18445/144606156-2597c32d-f20f-48b0-a531-9022672a4b2f.png">

**Comment by grololo06** [comment]
There is no space for the full lineage in the history so I just add the last "full name" into the table. The microseconds look a bit too much as well :)

**Comment by grololo06** [comment]
Fixed in 2.6.2.
