### ISSUE TITLE
Add internal taxonomic id to DOI export

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa#778]
Currently the DOI export creates a folder called `images` with subfolders by taxon. The name of those subfolders is the `display_name` (modified to replace the `<` by `_` for Windows compatibility 🤬). These names are somewhat volatile because (i) taxonomy changes and (ii) the display name contains the name of the parent for disambiguation (a first export could be made where the display name is "male" because it was the only one in the taxo db, the same category will be displayed as "male<Copepoda" is another "male" category is created somewhere else in the db).

To alleviate this problem while keeping the folder names human-readable, they should be constructed as `displayName__internalTaxoID` + the `internalTaxoID` should be added as a column in the exported TSV (probably named `object_annotation_category_id`.

NB: the `__` double underscore is necessary to clearly disambiguate from `_` which can exist in the taxon `display_name`.

**Comment by grololo06** [comment]
Fixed in 2.6.2.
