### ISSUE TITLE
Retirer le lien pour Download Ecotaxa

### ISSUE THREAD

**Issue by picheral** [ecotaxa/ecotaxa#813]
Sur la page d'accueil :
![image](https://user-images.githubusercontent.com/18468240/168298190-c4dcf8c7-8742-4db5-9989-fd59586a9f23.png)

**Comment by bea777515** [comment]
Bonjour, 
J'ai supprimé la ligne de la page d'accueil. 
J'enverrai le commit relatif (#813) avec d'autres (#794 #734 et peut-être #808) en début de semaine prochaine. 
Bien cordialement, 

De: "picheral" ***@***.***> 
À: "ecotaxa/ecotaxa" ***@***.***> 
Cc: "bea777515" ***@***.***>, "Assign" ***@***.***> 
Envoyé: Vendredi 13 Mai 2022 15:51:56 
Objet: Re: [ecotaxa/ecotaxa] Retirer le lien pour Download Ecotaxa (Issue #813) 





Assigned [ https://github.com/ecotaxa/ecotaxa/issues/813 | #813 ] to [ https://github.com/bea777515 | @bea777515 ] .

**Comment by grololo06** [comment]
This part of the home page is customizable, see contents of `/home/ecotaxa/front_mnt `directory on production machine. I just edited the file and the link is gone.

**Comment by grololo06** [comment]
I took the occasion to credit dev team and remove Altidev from which little code is left now.
![image](https://user-images.githubusercontent.com/20199778/170427850-b50a46d7-2f02-4785-9412-8f6f90d76247.png)
