### ISSUE TITLE
Sample information on map is not pulled from the correct project

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa#815]
In https://ecotaxa.obs-vlfr.fr/prj/6048 (MOOSE GE)
The information is
![image (4)](https://user-images.githubusercontent.com/18445/169054724-fa73af7d-0572-4db7-bebd-7dde13cb9778.png)

In https://ecotaxa.obs-vlfr.fr/prj/51 (Gatekeeper)
The information is
<img width="210" alt="Screenshot 2022-05-18 at 15 50 30" src="https://user-images.githubusercontent.com/18445/169056084-62bbc048-f5b7-47c9-ae69-897416f30cbe.png">

**Comment by jiho** [comment]
As a likely consequence, when the user is not app manager, he/she often gets the message
![image (3)](https://user-images.githubusercontent.com/18445/169054693-3c5e58d0-5491-4b5e-827d-16f61d522912.png)
because he/she does not have the permissions on the project from which the info is pulled.

**Comment by bea777515** [comment]
It takes the project id instead of the sample id in the request

**Comment by bea777515** [comment]
done
