### ISSUE TITLE
page 2 Train&Predict : deletion of input not possible

### ISSUE THREAD

**Issue by Elineau** [ecotaxa/ecotaxa#817]
Train&Predict tool, second page : 
when you select one category in the last column of this page, it is possible to edit it but it's impossible to remove it.

**Comment by grololo06** [comment]
Column is "Appear as category" one, e.g. Pterygota below:
![image](https://user-images.githubusercontent.com/20199778/169741965-ed5f5183-0891-4535-bd5f-00687c7956f1.png)

**Comment by grololo06** [comment]
Reloading the full page or playing with "Make categories appear like in" select works but for _all_ mapped categories so it's not very handy.

**Comment by bea777515** [comment]
missing  allowClear = true  and placeholder to select2 config in prediction_create_lsttaxo.html
