### ISSUE TITLE
Importing a zip file of a few MB is impossible

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa#818]
In the import page, a zip file can be imported and is said to be limited to 100MB. However, trying to upload a smaller file still results in an error `413 Request Entity Too Large` from nginx.

Here is a file which results in an error ftp://ftp_plankton@plankton.obs-vlfr.fr/Ecotaxa_Data_to_import/SYKE/ecotaxa-ifcb-labeled-uto-2021-1of10.zip (~56MB)

This is likely a configuration issue with nginx.

Expected fix: configure nginx to accept larger files. I would suggest to even up the limit to 500MB and test whether that works from a "slow" connection (it is 2022 after all, even a phone connection is very good).

**Comment by jiho** [comment]
NB: this upload solution is likely to be the easiest to reach from the API and therefore will be used in automated workflows.

**Comment by bea777515** [comment]
it is 20M on nginx.

**Comment by grololo06** [comment]
> NB: this upload solution is likely to be the easiest to reach from the API and therefore will be used in automated workflows.

There is a different route when going to /api/something (see /etc/nginx/sites-available/ecotaxa on the production box)

**Comment by bea777515** [comment]
/etc/nginx/nginx.conf 
client_max_body_size 670M;
client_body_timeout  360;

**Comment by jiho** [comment]
The message on the import page should therefore be updated:

> Only for < 100MB zip files.

=>

> Only for < 500MB zip files.

(which is a bit below what nginx allows but gives some lee room).
