### ISSUE TITLE
Difference in country treatment between self-registration and admin form

### ISSUE THREAD

**Issue by grololo06** [ecotaxa/ecotaxa#820]
Self-reg:

![image](https://user-images.githubusercontent.com/20199778/170321301-32ff0149-bb6c-46f6-8b74-135ff6307e3b.png)
The field is mandatory, form cannot be submitted without a value

Admin form:

![image](https://user-images.githubusercontent.com/20199778/170321558-eb679926-39ba-4435-b9de-4137d45d829e.png)
The field is not mandatory, the country can be erased and then one gets a server-side error.

![image](https://user-images.githubusercontent.com/20199778/170321835-36a062d2-f2bb-4a4a-985a-12ad3041b7fd.png)

**Comment by jiho** [comment]
A user for whom the country appeared empty reports
> i am from Israel. When I tried to add it, the system wrote another, so that's what I registered.

So it is possible that an admin erased it because it was wrong.

**Comment by bea777515** [comment]
Country select2 is case sensitive on public registration ( should not be ?). 
 country is now 'required' on user creation in admin (admin/views/users.py)
